"""GDDR5 timing parameters."""

GDDR5= {
    "tRAS": 36,
    "tRCDRD": 12,
    "tRCDWR": 7,
    "tRC": 48,
    "tRP": 12,
    "tRTP": 4,
    "tCCDL": 4,
    "tRTW": 12,
    "tRFCPB": 160,
    "tWRPRE": 6,
    "tWRRD_L": 4,
    "tRRDL": 4,
    "tPPD": 1,
    "tRREFD": 9,
    "tRRDS": 2,
    "tPD": 6,
    "tXPN": 8,
    "tRDSRE": 16,
    "tCCDS": 2,
    "tRFC": 600,
    "tCKE": 3,
    "tLK": 10,
    "tXS": 20,
    "tWRSRE": 16,
    "tWRRD_S": 2,
    "tWRRD_R": 2,
    "tRDWR_R": 12,
    "tRTRS": 1,
    "tFAW": 32,
    "t32AW": 256,
    "tCK": 1,
}