"""HBM2 timing parameters."""

HBM2 = {
    "tCCDL": 4,
    "tCCDS": 4,
    "tCCDR": 4,
    "tCKE": 3,
    "tPD": 3,
    "tCKESR": 4,
    "tRAS": 28,
    "tRC": 38,
    "tRFC": 88,
    "tRL": 10,
    "tRP": 10,
    "tRTP": 6,
    "tFAW": 24,
    "tWL": 8,
    "tWR": 12,
    "tXP": 6,
    "tXS": 96,
    "tCK": 1,
    "tRREFD": 14,
    "tRFCSB": 60,
    "tRCDRD": 14,
    "tRCDWR": 10,
    "tRRDL": 4,
    "tRRDS": 3,
    "tWTRL": 8,
    "tWTRS": 3,
    "tRDPDE": 6,
    "tPL": 6,
    "tRTW": 6,
}
