"""LPDDR4 timing parameters."""

LPDDR4 = {
    "tCCD": 4,
    "tCKE": 3,
    "tRAS": 28,
    "tRCpb": 34,
    "tRCD": 10,
    "tRFCpb": 75,
    "tRFCab": 170,
    "tRL": 10,
    "tRPab": 10,
    "tRPpb": 10,
    "tRRD": 5,
    "tRTP": 6,
    "tFAW": 24,
    "tWL": 8,
    "tRTRS": 1,
    "tWR": 12,
    "tWTR": 6,
    "tXP": 6,
    "tCK": 1,
    "tXSR": 100,
    "tDQSCK": 3,
    "tPPD": 4,
    "tCMDCKE": 2,
    "tDQS2DQ": 1,
    "tDQSS": 1,
    "tRPST": 1.5,
    "tSR": 2,
    "tWPRE": 2,
}
